// Vendor the two brand fonts (Schibsted Grotesk, Spline Sans Mono) from
// Google Fonts so the site carries no third-party request. Re-run to refresh:
// `node scripts/fetch-fonts.mjs`. Every unicode-range Google ships is kept
// (browsers only download the ranges a page uses), and the generated
// fonts.css + woff2 files are committed; Vite fingerprints the url()s at
// build time.
//
// Both families are shipped by Google as *variable* fonts: one file per
// (family, subset) carrying the whole wght axis. Asking the css2 API for
// discrete weights (`wght@400;500;700`) therefore yields three @font-face
// rules pointing at the same byte-identical file — which is what this repo
// used to vendor: twelve rules, four files, and a reviewer's reasonable
// conclusion that all medium/bold was synthesised. It is not; a single-value
// `font-weight` descriptor instances the axis at that weight. But it is
// twelve rules doing four rules' work, so we ask for the axis range instead
// and get the honest shape: four faces, `font-weight: <min> <max>`.
//
// Two assertions below keep that guarantee from rotting: every file must
// carry an `fvar` table (a static instance smuggled in here would silently
// become fake bold at every weight but one), and the four files must hash
// differently (a family/subset collapsing to one file means the subsetting
// broke).
import { createHash } from "node:crypto";
import { mkdir, rm, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { woff2Tables } from "./woff2-tables.mjs";

// Axis ranges are the weights docs/DESIGN.md §3 declares: the grotesk speaks
// at 400/500/700, the mono carries data at 400/500/600.
const CSS_URL =
  "https://fonts.googleapis.com/css2?family=Schibsted+Grotesk:wght@400..700&family=Spline+Sans+Mono:wght@400..600&display=swap";

// One face per family per subset — assert the shape we expect back.
const EXPECTED_FACES = 4;

// `swap` over `optional`/`block`: text must never be invisible, and the two
// latin faces are preloaded from Layout.astro, so the swap window is the
// preload's round trip rather than a full render-blocking wait. The value is
// rewritten here rather than inherited from Google so it stays ours.
const FONT_DISPLAY = "swap";

// A modern browser UA makes Google serve woff2 with subset comments.
const UA =
  "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36";

const outDir = fileURLToPath(new URL("../src/styles/fonts/", import.meta.url));
const cssPath = fileURLToPath(new URL("../src/styles/fonts.css", import.meta.url));

const slug = (s) =>
  s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

// The woff2 table reader lives in ./woff2-tables.mjs so tests/fonts.test.ts can
// assert the same invariant against the committed files on every CI run, not
// only when someone re-runs this script.

// --- fetch -------------------------------------------------------------

const res = await fetch(CSS_URL, { headers: { "user-agent": UA } });
if (!res.ok) throw new Error(`fonts css: HTTP ${res.status}`);
const css = await res.text();

// Each @font-face block is preceded by a `/* subset */` comment.
const blocks = [...css.matchAll(/\/\* ([a-z-]+) \*\/\s*(@font-face\s*\{[^}]+\})/g)];
if (blocks.length !== EXPECTED_FACES) {
  throw new Error(`expected ${EXPECTED_FACES} @font-face blocks, parsed ${blocks.length}`);
}

await rm(outDir, { recursive: true, force: true });
await mkdir(outDir, { recursive: true });

let out = "/* Generated by scripts/fetch-fonts.mjs — do not edit by hand. */\n";
const hashes = new Map();

for (const [, subset, block] of blocks) {
  const family = block.match(/font-family:\s*'([^']+)'/)?.[1];
  const weight = block.match(/font-weight:\s*(\d+\s+\d+)/)?.[1];
  const url = block.match(/url\((https:[^)]+\.woff2)\)/)?.[1];
  if (!family || !url) throw new Error(`unparsed block:\n${block}`);
  // A single-value descriptor means Google served a discrete weight — the
  // twelve-rules-four-files shape this script exists to avoid.
  if (!weight) throw new Error(`${family} ${subset}: expected a weight range, got:\n${block}`);

  const file = `${slug(family)}-${subset}.woff2`;
  const fontRes = await fetch(url, { headers: { "user-agent": UA } });
  if (!fontRes.ok) throw new Error(`${file}: HTTP ${fontRes.status}`);
  const bytes = Buffer.from(await fontRes.arrayBuffer());

  // The guarantee: a variable file renders every weight in the range for
  // real. Without fvar the browser synthesises everything above 400.
  const tables = woff2Tables(bytes);
  if (!tables.includes("fvar")) {
    throw new Error(`${file}: no fvar table — this is a static instance, weights would be faked`);
  }

  const hash = createHash("sha256").update(bytes).digest("hex");
  const clash = [...hashes].find(([, h]) => h === hash)?.[0];
  if (clash) throw new Error(`${file} is byte-identical to ${clash} — subsetting broke`);
  hashes.set(file, hash);

  await writeFile(`${outDir}${file}`, bytes);
  out += `\n${block
    .replace(/url\(https:[^)]+\.woff2\)\s*format\('woff2'\)/, `url('./fonts/${file}') format('woff2')`)
    .replace(/font-display:\s*[a-z]+;/, `font-display: ${FONT_DISPLAY};`)}\n`;
}

await writeFile(cssPath, out, "utf8");
console.log(`fonts  wrote ${hashes.size} variable faces to src/styles/fonts/ + fonts.css`);
for (const [file, hash] of hashes) console.log(`       ${hash.slice(0, 16)}  ${file}`);
