// Vendor the two brand fonts (Schibsted Grotesk, Spline Sans Mono) from
// Google Fonts so the site carries no third-party request. Re-run to refresh:
// `node scripts/fetch-fonts.mjs`. Every unicode-range Google ships is kept
// (browsers only download the ranges a page uses), and the generated
// fonts.css + woff2 files are committed; Vite fingerprints the url()s at
// build time.
import { mkdir, rm, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const CSS_URL =
  "https://fonts.googleapis.com/css2?family=Schibsted+Grotesk:wght@400;500;700&family=Spline+Sans+Mono:wght@400;500;600&display=swap";

// A modern browser UA makes Google serve woff2 with subset comments.
const UA =
  "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36";

const outDir = fileURLToPath(new URL("../src/styles/fonts/", import.meta.url));
const cssPath = fileURLToPath(new URL("../src/styles/fonts.css", import.meta.url));

const slug = (s) =>
  s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

const res = await fetch(CSS_URL, { headers: { "user-agent": UA } });
if (!res.ok) throw new Error(`fonts css: HTTP ${res.status}`);
const css = await res.text();

await rm(outDir, { recursive: true, force: true });
await mkdir(outDir, { recursive: true });

// Each @font-face block is preceded by a `/* subset */` comment.
const blocks = [...css.matchAll(/\/\* ([a-z-]+) \*\/\s*(@font-face\s*\{[^}]+\})/g)];
if (blocks.length === 0) throw new Error("no @font-face blocks parsed");

let out = `/* Generated by scripts/fetch-fonts.mjs — do not edit by hand. */\n`;
let count = 0;
for (const [, subset, block] of blocks) {
  const family = block.match(/font-family:\s*'([^']+)'/)?.[1];
  const weight = block.match(/font-weight:\s*(\d+)/)?.[1];
  const url = block.match(/url\((https:[^)]+\.woff2)\)/)?.[1];
  if (!family || !weight || !url) throw new Error(`unparsed block:\n${block}`);
  const file = `${slug(family)}-${weight}-${subset}.woff2`;
  const fontRes = await fetch(url, { headers: { "user-agent": UA } });
  if (!fontRes.ok) throw new Error(`${file}: HTTP ${fontRes.status}`);
  await writeFile(`${outDir}${file}`, Buffer.from(await fontRes.arrayBuffer()));
  out += `\n${block.replace(/url\(https:[^)]+\.woff2\)\s*format\('woff2'\)/, `url('./fonts/${file}') format('woff2')`)}\n`;
  count += 1;
}

await writeFile(cssPath, out, "utf8");
console.log(`fonts  wrote ${count} faces to src/styles/fonts/ + fonts.css`);
